//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JD.BookOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string BookName { get; set; }
        public string Author { get; set; }
        public string Press { get; set; }
        public Nullable<System.DateTime> Presstime { get; set; }
        public string ISBN { get; set; }
        public string Smallpic { get; set; }
        public string Bigpic { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public Nullable<decimal> NewPrice { get; set; }
        public string Introduce { get; set; }
        public string Detail { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> ChildId { get; set; }
        public Nullable<int> Discuss { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<System.DateTime> Reserve1 { get; set; }
        public Nullable<int> Reserve2 { get; set; }
        public string Reserve3 { get; set; }
        public string Reserve4 { get; set; }
        public string Reserve5 { get; set; }
    }
}
