//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JD.BookOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        public int Id { get; set; }
        public string FriendshipMsg { get; set; }
        public string FriendshipUrl { get; set; }
        public Nullable<int> FriendshipClass { get; set; }
        public string FriendshipDetail { get; set; }
        public Nullable<int> IsDIY { get; set; }
    }
}
