//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JD.BookOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Orders = new HashSet<Orders>();
            this.Shopping_Cart = new HashSet<Shopping_Cart>();
        }
    
        public int Id { get; set; }
        public string MemberId { get; set; }
        public string MemberPwd { get; set; }
        public string EMail { get; set; }
        public Nullable<long> Tell { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string HeadIco { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Registertime { get; set; }
        public string Sendaddress { get; set; }
        public string Reserve1 { get; set; }
        public Nullable<int> Reserve2 { get; set; }
        public string Reserve3 { get; set; }
        public string Reserve4 { get; set; }
        public string Reserve5 { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<Shopping_Cart> Shopping_Cart { get; set; }
    }
}
