//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JD.BookOA.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Online_bookstoreEntities : DbContext
    {
        public Online_bookstoreEntities()
            : base("name=Online_bookstoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Book> Book { get; set; }
        public DbSet<ChildClass> ChildClass { get; set; }
        public DbSet<Friendship> Friendship { get; set; }
        public DbSet<Member> Member { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<ParentClass> ParentClass { get; set; }
        public DbSet<schildclass> schildclass { get; set; }
        public DbSet<Shopping_Cart> Shopping_Cart { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<CarouselImg> CarouselImg { get; set; }
    }
}
